name: Daily Kanji Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Every day at 2PM UTC - Equivalent to AEST

jobs:
  run-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CockroachDB CLI
        run: |
          curl https://binaries.cockroachdb.com/cockroach-sql-v25.2.2.linux-amd64.tgz | tar -xz
          sudo cp cockroach-sql-v25.2.2.linux-amd64/cockroach-sql /usr/local/bin/

      - name: Run Query
        env:
          COCKROACH_URL: ${{ secrets.COCKROACH_URL }}
        run: |
          cockroach-sql --url "$COCKROACH_URL" --file=database/create-daily.sql
